
package com.hzih.stp.haian;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "add", targetNamespace = "org.demo.webservice/add", wsdlLocation = "http://10.36.1.244:8888/WA/services/add?wsdl")
public class Add extends Service {

    private static URL ADD_WSDL_LOCATION;
    private static WebServiceException ADD_EXCEPTION;
    private final static QName ADD_QNAME = new QName("org.demo.webservice/add", "add");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.36.1.244:8888/WA/services/add?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADD_WSDL_LOCATION = url;
        ADD_EXCEPTION = e;
    }

   /* public Add(String u) {
        super(__getWsdlLocation(), ADD_QNAME);
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(u);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADD_WSDL_LOCATION = url;
        ADD_EXCEPTION = e;
    }*/

    public Add(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADD_QNAME, features);
    }

    public Add(URL wsdlLocation) {
        super(wsdlLocation, ADD_QNAME);
    }

    public Add(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADD_QNAME, features);
    }

    public Add(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Add(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddPortType
     */
    @WebEndpoint(name = "addHttpPort")
    public AddPortType getAddHttpPort() {
        return super.getPort(new QName("org.demo.webservice/add", "addHttpPort"), AddPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddPortType
     */
    @WebEndpoint(name = "addHttpPort")
    public AddPortType getAddHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("org.demo.webservice/add", "addHttpPort"), AddPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADD_EXCEPTION!= null) {
            throw ADD_EXCEPTION;
        }
        return ADD_WSDL_LOCATION;
    }

}
