
package com.hzih.stp.haian;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "addPortType", targetNamespace = "org.demo.webservice/add")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddPortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @return
     *     returns com.hzih.ArrayOfArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "org.demo.webservice/add")
    @RequestWrapper(localName = "getDataDw", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataDw")
    @ResponseWrapper(localName = "getDataDwResponse", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataDwResponse")
    public ArrayOfArrayOfString getDataDw(
            @WebParam(name = "in0", targetNamespace = "org.demo.webservice/add")
            String in0,
            @WebParam(name = "in1", targetNamespace = "org.demo.webservice/add")
            String in1,
            @WebParam(name = "in2", targetNamespace = "org.demo.webservice/add")
            String in2,
            @WebParam(name = "in3", targetNamespace = "org.demo.webservice/add")
            String in3,
            @WebParam(name = "in4", targetNamespace = "org.demo.webservice/add")
            int in4,
            @WebParam(name = "in5", targetNamespace = "org.demo.webservice/add")
            int in5,
            @WebParam(name = "in6", targetNamespace = "org.demo.webservice/add")
            int in6);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @return
     *     returns com.hzih.ArrayOfArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "org.demo.webservice/add")
    @RequestWrapper(localName = "getDataDwDb", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataDwDb")
    @ResponseWrapper(localName = "getDataDwDbResponse", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataDwDbResponse")
    public ArrayOfArrayOfString getDataDwDb(
            @WebParam(name = "in0", targetNamespace = "org.demo.webservice/add")
            String in0,
            @WebParam(name = "in1", targetNamespace = "org.demo.webservice/add")
            String in1,
            @WebParam(name = "in2", targetNamespace = "org.demo.webservice/add")
            String in2,
            @WebParam(name = "in3", targetNamespace = "org.demo.webservice/add")
            String in3,
            @WebParam(name = "in4", targetNamespace = "org.demo.webservice/add")
            int in4,
            @WebParam(name = "in5", targetNamespace = "org.demo.webservice/add")
            int in5,
            @WebParam(name = "in6", targetNamespace = "org.demo.webservice/add")
            int in6);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "org.demo.webservice/add")
    @RequestWrapper(localName = "getDataCount", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataCount")
    @ResponseWrapper(localName = "getDataCountResponse", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataCountResponse")
    public String getDataCount(
            @WebParam(name = "in0", targetNamespace = "org.demo.webservice/add")
            String in0,
            @WebParam(name = "in1", targetNamespace = "org.demo.webservice/add")
            String in1,
            @WebParam(name = "in2", targetNamespace = "org.demo.webservice/add")
            String in2,
            @WebParam(name = "in3", targetNamespace = "org.demo.webservice/add")
            int in3,
            @WebParam(name = "in4", targetNamespace = "org.demo.webservice/add")
            int in4,
            @WebParam(name = "in5", targetNamespace = "org.demo.webservice/add")
            int in5);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @return
     *     returns com.hzih.ArrayOfArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "org.demo.webservice/add")
    @RequestWrapper(localName = "getDataDwAll", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataDwAll")
    @ResponseWrapper(localName = "getDataDwAllResponse", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataDwAllResponse")
    public ArrayOfArrayOfString getDataDwAll(
            @WebParam(name = "in0", targetNamespace = "org.demo.webservice/add")
            String in0,
            @WebParam(name = "in1", targetNamespace = "org.demo.webservice/add")
            String in1,
            @WebParam(name = "in2", targetNamespace = "org.demo.webservice/add")
            String in2,
            @WebParam(name = "in3", targetNamespace = "org.demo.webservice/add")
            String in3,
            @WebParam(name = "in4", targetNamespace = "org.demo.webservice/add")
            int in4,
            @WebParam(name = "in5", targetNamespace = "org.demo.webservice/add")
            int in5,
            @WebParam(name = "in6", targetNamespace = "org.demo.webservice/add")
            int in6);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @return
     *     returns com.hzih.ArrayOfArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "org.demo.webservice/add")
    @RequestWrapper(localName = "getData", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataResponse")
    public ArrayOfArrayOfString getData(
            @WebParam(name = "in0", targetNamespace = "org.demo.webservice/add")
            String in0,
            @WebParam(name = "in1", targetNamespace = "org.demo.webservice/add")
            String in1,
            @WebParam(name = "in2", targetNamespace = "org.demo.webservice/add")
            String in2,
            @WebParam(name = "in3", targetNamespace = "org.demo.webservice/add")
            int in3,
            @WebParam(name = "in4", targetNamespace = "org.demo.webservice/add")
            int in4,
            @WebParam(name = "in5", targetNamespace = "org.demo.webservice/add")
            int in5);

    /**
     * 
     * @param in0
     * @return
     *     returns com.hzih.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "org.demo.webservice/add")
    @RequestWrapper(localName = "getFzData", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetFzData")
    @ResponseWrapper(localName = "getFzDataResponse", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetFzDataResponse")
    public ArrayOfString getFzData(
            @WebParam(name = "in0", targetNamespace = "org.demo.webservice/add")
            String in0);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns com.hzih.ArrayOfArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "org.demo.webservice/add")
    @RequestWrapper(localName = "getDataAll", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataAll")
    @ResponseWrapper(localName = "getDataAllResponse", targetNamespace = "org.demo.webservice/add", className = "com.hzih.GetDataAllResponse")
    public ArrayOfArrayOfString getDataAll(
            @WebParam(name = "in0", targetNamespace = "org.demo.webservice/add")
            String in0,
            @WebParam(name = "in1", targetNamespace = "org.demo.webservice/add")
            String in1,
            @WebParam(name = "in2", targetNamespace = "org.demo.webservice/add")
            String in2,
            @WebParam(name = "in3", targetNamespace = "org.demo.webservice/add")
            int in3,
            @WebParam(name = "in4", targetNamespace = "org.demo.webservice/add")
            int in4);

}
